"""add allow_location_tags

Revision ID: 940a0123b7b9
Revises: 20260803_1400_add_is_deleted
Create Date: 2026-08-07 20:30:29.866084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940a0123b7b9'
down_revision: Union[str, None] = '20260803_1400_add_is_deleted'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('achievement_id', sa.String(length=100), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='_user_achievement_uc')
    )
    op.create_index(op.f('ix_user_achievements_unlocked_at'), 'user_achievements', ['unlocked_at'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.add_column(
        'users',
        sa.Column(
            'allow_location_tags',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )   
    op.add_column('waves', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('waves', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('waves', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waves', 'country')
    op.drop_column('waves', 'state')
    op.drop_column('waves', 'city')
    op.drop_column('users', 'allow_location_tags')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_unlocked_at'), table_name='user_achievements')
    op.drop_table('user_achievements')
    # ### end Alembic commands ###
