"""add_hashtags

Revision ID: fc9e017a02f5
Revises: ba46d1030eb2
Create Date: 2026-08-03 12:03:09.467780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9e017a02f5'
down_revision: Union[str, None] = 'ba46d1030eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtags_tag'), 'hashtags', ['tag'], unique=True)
    op.create_table('wave_hashtags',
    sa.Column('wave_id', sa.String(length=36), nullable=False),
    sa.Column('hashtag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wave_id'], ['waves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wave_id', 'hashtag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wave_hashtags')
    op.drop_index(op.f('ix_hashtags_tag'), table_name='hashtags')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
