"""Add country and phone_number columns to User model

Revision ID: 7d836dfa2bbc
Revises: 0003_reconcile_schema
Create Date: 2026-08-01 11:12:38.184703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d836dfa2bbc'
down_revision: Union[str, None] = '0003_reconcile_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('polls_wave_id_key'), 'polls', type_='unique')
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_waves_parent_wave_id'), table_name='waves')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_waves_parent_wave_id'), 'waves', ['parent_wave_id'], unique=False)
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'country')
    op.create_unique_constraint(op.f('polls_wave_id_key'), 'polls', ['wave_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
