"""add_deactivation_fields

Revision ID: ba46d1030eb2
Revises: 7260377507bb
Create Date: 2026-08-03 11:45:23.868464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba46d1030eb2'
down_revision: Union[str, None] = '7260377507bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deactivated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.alter_column('wave_circles', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wave_circles', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'deactivated_at')
    op.drop_column('users', 'is_deactivated')
    # ### end Alembic commands ###
