"""add profile fields

Revision ID: 7260377507bb
Revises: 7d836dfa2bbc
Create Date: 2026-08-02 17:35:01.225343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7260377507bb'
down_revision: Union[str, None] = '7d836dfa2bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('wave_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wave_id'], ['waves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'wave_id', name='_user_wave_bookmark_uc')
    )
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_wave_id'), 'bookmarks', ['wave_id'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('users', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('twitter_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pinned_wave_id', sa.String(length=36), nullable=True))
    op.alter_column('wave_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('wave_circles',sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('waves', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_waves_spread_from_id'), 'waves', ['spread_from_id'], unique=False)
    op.drop_constraint(op.f('waves_spread_from_id_fkey'), 'waves', type_='foreignkey')
    op.create_foreign_key(None, 'waves', 'waves', ['spread_from_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waves', type_='foreignkey')
    op.create_foreign_key(op.f('waves_spread_from_id_fkey'), 'waves', 'waves', ['spread_from_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_waves_spread_from_id'), table_name='waves')
    op.alter_column('waves', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('wave_circles', 'is_public')
    op.alter_column('wave_alerts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'pinned_wave_id')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'twitter_url')
    op.drop_column('users', 'website')
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_bookmarks_wave_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
